![title](https://image.ibb.co/erDntK/logo2018.png)

---

# Simple Linear Classification

In this assignment you will practice putting together a simple image classification pipeline, based on the SVM and Softmax classifier. 

The goals of this assignment are as follows:
* understand the basic Image Classification pipeline and the data-driven approach (train/predict stages)
* understand the train/val/test splits and the use of validation data for hyperparameter tuning.
* develop proficiency in writing efficient vectorized code with numpy

* implement and apply a Softmax classifier
* implement and apply a Multiclass Support Vector Machine (SVM) classifier

* understand the differences and tradeoffs between these classifiers

---
## 0 - Import necessary libraries and informations

In [0]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


np.set_printoptions(precision=8)

Write down your Name and Student ID

In [0]:
NIM = 123456
Nama = ""

---
## 1 - Load CIFAR-10 Dataset

* First, Obtain Cifar-10 dataset.
  There are from various source in Internet like [Keras](https://keras.io/datasets/), [Tensorflow](https://www.tensorflow.org/api_docs/python/tf/keras/datasets), or any other source
* Next you will prepare the dataset by first:
 * visualizing data
 * split into training, validation, and testing set
 * normalize data

---
### a. Import Data ***CIFAR-10***
<br>

**EXERCISE**: 
* `load Cifar-10 dataaset.`
* `It should consists of 50000 32x32 images for training and 10000 of the same shape for testing.`

In [0]:
(X_train, y_train), (X_test, y_test) = ??

classes = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'forse', 'ship', 'truck']

Check your implementation

In [0]:
print('X_train.shape =',X_train.shape)
print('y_train.shape =',y_train.shape)
print('X_test.shape  =',X_test.shape)
print('y_test.shape  =',y_test.shape)

**Expected Output**: 
<pre>
X_train.shape = (50000, 32, 32, 3)
y_train.shape = (50000, 1)
X_test.shape  = (10000, 32, 32, 3)
y_test.shape  = (10000, 1)


---
### b. Visualizing Data


Show the first 20 images from X_train

In [0]:
fig, ax = plt.subplots(2,10,figsize=(15,4.5))
fig.subplots_adjust(hspace=0.1, wspace=0.1)
for j in range(0,2):
    for i in range(0, 10):
        ax[j,i].imshow(X_train[i+j*10])
        ax[j,i].set_title(classes[y_train[i+j*10,0]])
        ax[j,i].axis('off')
plt.show()

---
### c. Split Training Data
<br>

**EXERCISE**: 
* Cut the `last 1000 data` from `Training Set`, and save it as `Validation Set`

In [0]:
X_val = ??
y_val = ??

X_train = ??
y_train = ??


Check your implementation

In [0]:
print('X_val.shape   =',X_val.shape)
print('y_val.shape   =',y_val.shape)
print('X_train.shape =',X_train.shape)
print('y_train.shape =',y_train.shape)

**Expected Output**: 
<pre>X_val.shape   = (1000, 32, 32, 3)
y_val.shape   = (1000, 1)
X_train.shape = (49000, 32, 32, 3)
y_train.shape = (49000, 1)

---
### d. Normalizing Data
<br>

**EXERCISE**: 
* Normalize `X_train`, `X_val`, and `X_test` by *zero-centering* them:
    1. calculate the `mean` of training data `X_train`
    * subtract `X_train`, `X_val`, and `X_test` using mean of `X_train`

In [0]:
X_train = X_train.astype('float32')
X_val = X_val.astype('float32')
X_test = X_test.astype('float32')

mean_image = ??
X_train = ??
X_val = ??
X_test = ??

Check your implementation

In [0]:
print('np.mean(X_train) =',np.mean(X_train))
print('np.mean(X_val)   =',np.mean(X_val))
print('np.mean(X_test)  =',np.mean(X_test))

**Expected Output**: 
<pre>np.mean(X_train) = -6.6769658e-06
np.mean(X_val)   = 0.89910334
np.mean(X_test)  = 0.83958524

---
### e. Reshape Data
<br>

**EXERCISE**: 
* Reshape each data in `X_train`, `X_val`, and `X_test` into 1-dimensional matrix 

*Hint: use `np.reshape()`*

In [0]:
X_train = ??
X_val = ??
X_test = ??

Check your implementation

In [0]:
print('X_train.shape =',X_train.shape)
print('X_val.shape   =',X_val.shape)
print('X_test.shape  =',X_test.shape)

**Expected Output**: 
<pre>X_train.shape = (49000, 3072)
X_val.shape   = (1000, 3072)
X_test.shape  = (10000, 3072)


**EXERCISE**:
* Reshape `y_train`, `y_val`, and `y_test` into a vector 

*Hint: use `np.ravel()`*

In [0]:
y_train = ??
y_val = ??
y_test = ??

Check your implementation

In [0]:
print('y_train.shape =',y_train.shape)
print('y_val.shape   =',y_val.shape)
print('y_test.shape  =',y_test.shape)

**Expected Output**: 
<pre>y_train.shape = (49000,)
y_val.shape   = (1000,)
y_test.shape  = (10000,)


---
## 2 - Linear Function
* Complete the forward and backward function of basic linear regression function


---
### a. Forward Function

<br>

**EXERCISE**: 
* Implement `forward function` for Linear Classifier as follow:

$$
\begin{align}
f(x, W, b) = x.W + b
\end{align}
$$

In [0]:
def forward(x, W, b):   
    v = ??    
    
    return v

Check your implementation

In [0]:
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

np.random.seed(2019)
W = np.random.random((3, 2)) 
b = np.zeros((1, 2))

v = forward(X, W, b)

print('v.shape =', v.shape, '\n')
print('v =')
print(v)

**Expected Output**: 
<pre>v.shape = (4, 2) 

v =
[[0.88049907 0.29917202]
 [1.50446903 0.93704942]
 [1.78398128 0.69225253]
 [2.40795124 1.33012993]]

---
### b. Backward Function
<br>

**EXERCISE**: 
* Implement `backward function` for Linear Classifier as follow:


$$
\begin{align*}
\partial W & = x^T.\partial out \\
\partial b & = \sum \partial out \\
\partial x & = \partial out.W^T \\
\end{align*}
$$

*Hint: use `axis=0` and `keepdims=True` to calculate $\partial b$*

In [0]:
def backward(dout, x, W, b):
    dW = ??
    db = ??
    dx = ??
    
    return dW, db, dx

Check your implementation

In [0]:
np.random.seed(2019)
dout = np.random.random((4, 2)) 
dW, db, dX = backward(dout, X, W, b)

In [0]:
print('dW.shape =', dW.shape)
print('dW =')
print(dW)

**Expected Output**: 
<pre>
dW.shape = (3, 2) 
dW =
[[1.58269734 1.20237818]
 [1.32616823 1.54108356]
 [3.11014951 2.23333609]]

In [0]:
print('db.shape =', db.shape)
print('db =', db)

**Expected Output**: 
<pre>db.shape = (1, 2)
db = [[3.11014951 2.23333609]]

In [0]:
print('dX.shape =', dX.shape)
print('dX =')
print(dX)

**Expected Output**: 
<pre>dX.shape = (4, 3)
dX =
[[0.9707924  0.81448293 0.91311394]
 [0.81448293 0.79622609 0.74024004]
 [0.91311394 0.74024004 0.86478251]
 [0.98945638 1.01428543 0.88849893]]


---
## 3 - Softmax Function

* A very important concept to understand in numpy is `"broadcasting"`. 
* It is very useful for performing mathematical operations between arrays of different shapes. 
* For the full details on broadcasting, you can read the official [broadcasting documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

---
### a. Softmax Score
<br>

**EXERCISE**: 
* Implement a `softmax score function` using numpy.


$\text{for a matrix } x \in \mathbb{R}^{m \times n}$

- $ n : \text{number of data}$
- $ m : \text{number of label}$

$\text{$x_{ij}$ maps to the element in the $i^{th}$ row and $j^{th}$ column of $x$}$ 

thus we have
$$softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix}$$

it is equal to
$$softmax(x)  = \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    ...  \\
    softmax\text{(last row of x)} \\
\end{pmatrix} $$

In [0]:
def softmax(x):
    """Calculates the softmax for each row of the input x.

Argument:
    x -- A numpy matrix of shape (n,m)

    Returns:
    score -- A numpy matrix equal to the softmax of x, of shape (n,m)
          -- normalized log probabilities score
    """
    
    # 1. COMPUTE THE CLASS PROBABILITIES    
    
    # shift x by subtracting with its maximum value . Use np.max(...)
    x = ??
    
    # Apply exp() element-wise to x. Use np.exp(...).    
    x_exp = ??

    # Create a vector X_sum that sums each row of X_exp. Use np.sum(..., axis = 1, keepdims = True).
    x_sum = ??
    
    # Compute softmax(x) score by dividing X_exp by X_sum. It should automatically use numpy broadcasting.
    score = ??
    
    return score

Check your implementation

In [0]:
x = np.array([
    [1, 3, 0, 1 ,1],
    [0, 2, 0, 1, 9],
    [0, 1, 0, 1, 0]])

np.random.seed(2019)
W = np.random.random((5, 2)) 
b = np.zeros((1, 2))

score = forward(x, W, b)

print("score = " )
print(score,'\n')
print("softmax(score) = " )
print(softmax(score))

**Expected Output**:
<pre>score = 
[[4.35897229 3.61566867]
 [9.88257553 5.83070915]
 [1.32616823 1.54108356]] 

softmax(score) = 
[[0.67771785 0.32228215]
 [0.98290735 0.01709265]
 [0.44647702 0.55352298]]

---
### b. Softmax Loss
<br>

**EXERCISE**: 
* Implement a `softmax loss` function using numpy. 
 
- Loss of the `i-th data` is the normalized log probability of the score at the class should be<br>
  $$L_i =  -\log(\frac{e^{X_{y_i}}}{\sum_{j}e^{X_{j}}})$$<br><br>
 
- The Softmax Loss is the average of all data loss<br>
  $$L = \frac{1}{N}\sum^N_{i=1}L_i$$

In [0]:
def softmax_loss(score, y):
    """Calculates the softmax loss for each row of the input x.
    
    Argument:
    score -- A numpy matrix equal to the softmax of x, of shape (n,m)
          -- normalized log probabilities score
          
    y     -- A numpy vector of shape(n,)
          -- containing training labels;
          -- y[i] = c means that X[i] has label c, where 0 <= c < C.

    Returns:
    dscore -- A numpy matrix equal to the softmax of x, of shape (n,m)
           -- gradient score of softmax
    """
    
    num_examples = score.shape[0]
        
    # 2. COMPUTE THE LOSS : average cross-entropy loss
    
    #make a number list containing [1 2 3 ... n]
    number_list = ??
    
    # calculate the correct log probability of score[number_list,y] by applycing -np.log(...)
    corect_logprobs = ??
    
    # average the correct log probability, use np.sum then divide it by num_examples
    loss = ??
    
    
    # 3. COMPUTE THE GRADIENT ON SCORES
    dscores = score
    dscores[range(num_examples),y] -= 1
    dscores /= num_examples

    
    return loss, dscores

Check your implementation

In [0]:
x = np.array([
    [1, 3, 0, 1 ,1],
    [0, 2, 0, 1, 9],
    [0, 1, 0, 1, 0]])

y = np.array([
    0, 1, 0
])

np.random.seed(2019)
W = np.random.random((5, 2)) 
b = np.zeros((1, 2))

score = forward(x, W, b)

print("score = " )
print(score, '\n')

score = softmax(score)
print("softmax(score) = " )
print(score,'\n')

loss, dscore = softmax_loss(score, y)
print('loss   =',loss, '\n')
print('dscore =')
print(dscore)

**Expected Output**:
<pre>score = 
[[4.35897229 3.61566867]
 [9.88257553 5.83070915]
 [1.32616823 1.54108356]] 

softmax(score) = 
[[0.67771785 0.32228215]
 [0.98290735 0.01709265]
 [0.44647702 0.55352298]] 

loss   = 1.7548327929166458 

dscore =
[[-0.10742738  0.10742738]
 [ 0.32763578 -0.32763578]
 [-0.18450766  0.18450766]]

---
## 4 - Train a Softmax Classifier
* Combine linear function and softmax function that you have completed to train a multiclass softmax classifier

---
### a. Weight Initialization
<br>

**EXERCISE**: 
* Implement `Weight initialization function`
    - receive input size `n`, number of neuron `d`, and standard deviation `std`
    - generate normal random matrix `W` of size `(n x d)` and multiply it by `std`
    - generate zeros matrix `b` of size `(1 x d)`

In [0]:
def initialize_weights(n, d, std):
    W = ??
    b = ?
    
    return W, b

---
### b. Training Function
<br>

**EXERCISE**: 
* Implement **Training Function**
    * call `forward function`
    * call `softmax function`
    * call `softmax_loss function`
    * call `backward function`
    * implement `weight update`

In [0]:
def train(X, y, W=None, b=None, learning_rate=1e-6, reg=1e4, num_iters=100, batch_size=200, verbose=False):
    
    num_classes = np.max(y) + 1 # assume y takes values 0...K-1 where K is number of classes
    
    # get number of training data and its dimension from X
    num_train, dim = ??
    
    # initialize new weights if W matrix is not provided
    # call initialize_weights function using dim, num_classes, and std=0.001
    if W is None:
        W, b = ??

    # Run stochastic gradient descent to optimize W
    loss_history = []
                     
    for it in range(num_iters):
        X_batch = None
        y_batch = None

        # Randomly select indices from training examples
        train_rows = np.arange(num_train)
        idxs = np.random.choice(train_rows, batch_size, replace=False)
  
        X_batch = X[idxs]
        y_batch = y[idxs]


        # calculate class score by calling forward function using X_batch, W, and b
        scores = ??
        
        # calculate softmax score by calling softmax function using scores
        softmaX_score = ??
        
        # evaluate loss and gradient by calling softmax_loss function using softmax_score and y_batch
        loss, dout = ??
    
        # append the loss history
        loss_history.append(loss)

        # calculate weights gradient by calling backward function using dout, X_batch, W, and b
        dW, db, _ = ??
        
        # perform regulatization gradient
        dW += reg*W
        
        # perform parameter update by subtracting W and b with a fraction of dW and db
        # according to the learning rate
        W -= ??
        b -= ??
        
        if verbose and it % 100 == 0:
            print ('iteration', it,'/',num_iters, ': loss =', loss)
    return loss_history, W, b

---
### c. Train the Softmax Classifier

Try the training Function using the initial parameter

In [0]:
loss, W, b = train(X_train, y_train)

Visualize the loss

In [0]:
plt.plot(loss)
plt.show()

**Expected Output**:
The graph should show that the loss is generally decreased as the training goes

---
### d. Predict Function
<br>

**EXERCISE**: 
* Implement **Predict Function**
    * call `forward function`

In [0]:
def predict(X, W, b):    
    y_pred = np.zeros(X.shape[1])

    
    # calculate class score by calling forward function using X, W, and b
    y_pred = ??
    
    # take the maximum prediction and use that column to get the class     
    y_pred = y_pred.argmax(axis=-1)
    
    return y_pred

Check your implementation

In [0]:
import sklearn
from sklearn.metrics import accuracy_score

y_pred = predict(X_train, W, b)
accuracy = sklearn.metrics.accuracy_score(y_train, y_pred)

print('Training Accuracy =', accuracy*100,'%')

print('Training label  =', y_test[:15])
print('Predicted label =', y_pred[:15])

**Expected Output**:

You should get about **`27-29%`** accuracy on training set using the initial run

---

In [0]:
y_pred = predict(X_val, W, b)
accuracy = sklearn.metrics.accuracy_score(y_val, y_pred)
print('Validation Accuracy =', accuracy*100,'%')

print('Validation label =',y_test[:15])
print('Predicted label  =',y_pred[:15])

**Expected Output**:

You should also get about **`27-29%`** accuracy on validation set

You can retrain further the weights by adding the pre-trained `W` and `b` to the arguments when calling training function


---
## 5 - Hyperparameter Tuning
* After you find that the classifier is working properly, next
* Find the best Learning Rate and Regularization Strength
<br>
<br>


**EXERCISE**: 
* Use the `validation set` to tune hyperparameters (regularization strength and learning rate). 
     * Greedily loop over `learning_rates` and `regulatization` to get all combination
     
     
* You **should** experiment with different ranges for the learning rates and regularization strengths; 




In [0]:
import warnings
warnings.filterwarnings('ignore')

results = {}
best_val = -1
best_W = None
best_b = None
learning_rates = [1e-6, 1e-7, 5e-7]
regularization_strengths = [2.5e4, 5e4]

iterations = 2000

# Greedily loop over learning_rates and regularization_strengths
for ??:
    for ??:
        print('Running {} iterations, rate = {}, reg = {}'.format(iterations, rate, reg))
        # call train function using the learning rate and regularization selected
        loss, W, b = train(X_train, y_train, 
                              learning_rate=??, reg=??,
                              num_iters=??, verbose=False)
        
        # call predict function using pretrained W and b on X_train and X_val to evaluate
        y_train_pred = predict(??, ??, ??)
        y_val_pred = predict(??, ??, ??)
        
        # calculate the accuracy
        train_accuracy = np.mean(y_train == y_train_pred)
        val_accuracy = np.mean(y_val == y_val_pred)
        
        print ('rate = {}, reg = {}, test accuracy = {}, validation accuracy = {}'.format(
            rate, reg, train_accuracy, val_accuracy))
        
        # store the result accuracy combination
        results[(rate, reg)] = (train_accuracy, val_accuracy)
        
        # store the best Weight and Bias
        if val_accuracy > best_val:
            best_W = W
            best_b = b
            best_val = val_accuracy


    
# Print out results.
for lr, reg in sorted(results):
    train_accuracy, val_accuracy = results[(lr, reg)]
    print('lr',lr,',reg',reg,', train accuracy: ',train_accuracy*100,'%, val accuracy: ', val_accuracy ,'%')
    
print()
print('best validation accuracy achieved during cross-validation:',best_val*100,'%')
print('best Weights and bias are stored in `best_W` and `best_b`')

**Expected Output**:

if you are careful you should be able to get a classification accuracy of **over 35%** on the validation set


---
## 6 - Try Another Hyperparameter Combination

Try to add another combination of learning rates and regularization strength hyperparameter, and repeat the `step 5`


---
## 7 - Test the Trained Weights

<br>

**EXERCISE**: 
* Test the **Best Weights and Bias** to the `X_test`

In [0]:
y_pred = predict(??, ??, ??)

accuracy = sklearn.metrics.accuracy_score(y_test, y_pred)

print('Testing Accuracy =', accuracy*100,'%')
print('Test label      =',y_test[:15])
print('Predicted label =',y_pred[:15])

**Expected Output**:

You should reach at least  **32%** accuracy on test set


---
## 8 - Vizualize the Trained Weights 

Visualize the learned weights for each class for each class


---
### a. Retrieve one class weights
Try to visualize one trained weights.<br><br>
**Note:** You can change the `id`

In [0]:
id = 0

# get the id-th column from best weight
w = ??

print('w.shape =',w.shape)

**Expected Output**:
<pre>
w.shape = (3072,)


---
### b. Normalize the weight for visualization
Image plot can only receive input range [0..1] for float type, or [0..255] for integer type, and the weights are not in those range.

So we need to normalize. Here we use MinMaxScaler from sklearn toolkit

In [0]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((0.05,.95))
w = scaler.fit_transform(w.reshape(-1, 1))

print('w.shape =',w.shape)

**Expected Output**:
<pre>
w.shape = (3072, 1)

---
### c. Visualize the weight 
Now reshape the weight back to (32,32,3), and plot the image. Use `np.reshape()`

In [0]:
w = ??

plt.figure(figsize=(2,2))
plt.imshow(w)
plt.title(classes[id])
plt.show()

---
### d. Do it to the other weights

In [0]:
fig, ax = plt.subplots(1,10,figsize=(18,5))
fig.subplots_adjust(hspace=0.1, wspace=0.1)
for i in range(0, 10):
    # get the i-th weight from best_W
    w = ??
    
    # normalize the weight (see previous example)
    w = ??
    
    # reshape the weight
    w = ??
    
    ax[i].imshow(w)
    ax[i].axis('off')
    ax[i].set_title(classes[i])
plt.show()

**Expected Output**:

You should see that the weights visualization should  match the ilustration below

![cifar10](http://cs231n.github.io/assets/templates.jpg)


---
## 9 - Linear Classifier: Multiclass SVM

---
### a. SVM Loss

<br>

**EXERCISE**: 
* Implement `Multiclass SVM Loss` or `Hinge Loss`

In [0]:
def svm_loss(score, y):
    """Calculates the smb loss for each row of the input x.
    
    Argument:
    score -- A numpy matrix equal to the softmax of x, of shape (n,m)
          -- normalized log probabilities score
          
    y     -- A numpy vector of shape(n,)
          -- containing training labels;
          -- y[i] = c means that X[i] has label c, where 0 <= c < C.

    Returns:
    dscore -- A numpy matrix equal to the softmax of x, of shape (n,m)
           -- gradient score of softmax
    """
    
    num_examples = score.shape[0]
    
    
    # 1. COMPUTE THE SVM LOSS
    
    # get the correct class score. Use np.choose( , ) using y and score.T
    correct_scores = ??
    
    # calculate margin: score.T subtracted by correct_score, then add by 1
    margin = ??
    
    # remove all margin below 0. Use np.maximum(0, margin)
    margin = ??
        
    # COMPUTE THE LOSS 
    # calculate SVM loss of each data: sum of margin of non-target class
    # simply total all the margin (use np.sum()), and subtract it by 1
    loss_i = ??
    
    
    
    # average loss_i by num_examples
    loss = ??
    
    
    # 2. COMPUTE THE GRADIENT ON SCORES
    # margins for the correct class have already been set to 0
    dscores = (margin.T > 0).astype(float)
    marginsSum = dscores.sum(1) - 1
    dscores[range(dscores.shape[0]), y] = -marginsSum
        
    return loss, dscores

Check your implementation

In [0]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0],
    [1, 0, 3, 5 ,0]])

y = np.array([
    0, 0, 1
])

np.random.seed(20)
W = np.random.random((5, 2)) 
b = np.zeros((1, 2))

score = forward(x, W, b)

print("score = " )
print(score)
print()

loss, dscore = svm_loss(score, y)
print('loss   =',loss)
print('dscore =')
print(dscore)

**Expected Output**:
<pre>
score = 
[[ 7.2556866  13.16988641]
 [ 8.57456925 10.36318348]
 [ 2.58920427  5.5655412 ]]

loss   = 3.234271348285095
dscore =
[[-1.  1.]
 [-1.  1.]
 [ 0. -0.]]


---

Notice the loss gradients resulted from SVM Loss. 

What's the difference between those gradients and Softmax Gradients?

What are the effects?

---
### b. Train Multiclass SVM Classifier
<br>

**EXERCISE**: 
* The same as the training function using Softmax before, complete the train function below, 
* but rather than using `softmax_loss`, use `svm_loss`

In [0]:
def train_svm(X, y, W=None, b=None, learning_rate=1e-6, reg=1e4, num_iters=100, batch_size=200, verbose=False):
    num_train, dim = X.shape
    num_classes = np.max(y) + 1 # assume y takes values 0...K-1 where K is number of classes
    
    if W is None:
        W = 0.001 * np.random.randn(dim, num_classes)
    if b is None:
        b = np.zeros((1,num_classes))

    # Run stochastic gradient descent to optimize W
    loss_history = []
                     
    for it in range(num_iters):
        X_batch = None
        y_batch = None

        # Randomly select indices from training examples
        train_rows = np.arange(num_train)
        idxs = np.random.choice(train_rows, batch_size, replace=False)
  
        X_batch = X[idxs]
        y_batch = y[idxs]


        # calculate class score by calling forward function using X_batch, W, and b
        scores = ??
                
        # evaluate loss and gradient by calling svm_loss function using score and y_batch
        loss, dout = ??
    
        # append the loss history
        loss_history.append(loss)

        # calculate weights gradient by calling backward function using dout, X_batch, W, and b
        dW, db, _ = ??
        
        # perform regulatization gradient
        dW += reg*W
        
        # perform parameter update by subtracting W and b with a fraction of dW and db
        # according to the learning rate
        W -= ??
        b -= ??
        
        if verbose and it % 100 == 0:
            print ('iteration', it,'/',num_iters, ': loss =', loss)
    return loss_history, W, b

---
### c. Hyperparameter Tuning for Multiclass SVM Classifier
<br>

**EXERCISE**: 
* Again, complete the codes below similar to the Hyperparameter tuning for `Softmax Classifier`

In [0]:
import warnings
warnings.filterwarnings('ignore')

results = {}
best_val = -1
best_W = None
best_b = None
learning_rates = [1e-6, 1e-7, 5e-7]
regularization_strengths = [3e4, 5e4]

iterations = 2000

# Greedily loop over learning_rates and regularization_strengths
for ??:
    for ??:
        print('Running {} iterations, rate = {}, reg = {}'.format(iterations, rate, reg))
        # call train function using the learning rate and regularization selected
        loss, W, b = train(X_train, y_train, 
                              learning_rate=??, reg=??,
                              num_iters=??, verbose=False)
        
        # call predict function using pretrained W and b on X_train and X_val to evaluate
        y_train_pred = predict(??, ??, ??)
        y_val_pred = predict(??, ??, ??)
        
        # calculate the accuracy
        train_accuracy = np.mean(y_train == y_train_pred)
        val_accuracy = np.mean(y_val == y_val_pred)
        
        print ('rate = {}, reg = {}, test accuracy = {}, validation accuracy = {}'.format(
            rate, reg, train_accuracy, val_accuracy))
        
        # store the result accuracy combination
        results[(rate, reg)] = (train_accuracy, val_accuracy)
        
        # store the best Weight and Bias
        if val_accuracy > best_val:
            best_W = W
            best_b = b
            best_val = val_accuracy

            
# Print out results.
for lr, reg in sorted(results):
    train_accuracy, val_accuracy = results[(lr, reg)]
    print('lr',lr,',reg',reg,', train accuracy: ', train_accuracy*100,'%, val accuracy: ', val_accuracy ,'%')
    
print()
print('best validation accuracy achieved during cross-validation:', best_val*100, '%')

**Expected Output**:

You should reach `at least`  **`30%`** accuracy on cross-validation

---
### d. Visualize the Weights Trained
<br>

**EXERCISE**: 
* complete the implementation to show the trained weight visualizations

In [0]:
fig, ax = plt.subplots(1,10,figsize=(18,5))
fig.subplots_adjust(hspace=0.1, wspace=0.1)
for i in range(0, 10):
    # get the i-th weight
    w = ??
    
    # normalize the weight
    w = ??
    
    # reshape the weight
    w = ??
    
    ax[i].imshow(w)
    ax[i].axis('off')
    ax[i].set_title(classes[i])
plt.show()

### Notice the difference in weight visualization
Describe what your visualized SVM weights look like. Think on why they look they way that they do.

---
---

# Congratulation, You've Completed Exercise 1

![footer](https://image.ibb.co/hAHDYK/footer2018.png)